package org.tbwork.anole.common.message.c_2_s;

import org.tbwork.anole.common.message.Message;
import org.tbwork.anole.common.message.MessageType;

import lombok.Data;

@Data
public abstract class C2SMessage extends Message{

	/**
	 * Global Id of Subscriber Client.
	 */
	private int clientId; 
	
	/**
	 * Global token for certain clientId, which is 
	 * generated by the server against invalid connection.
	 */
	private int token;
	
    public C2SMessage(){};
	
	public C2SMessage(MessageType msgType){
		 super(msgType);
	}
	
}
