package org.anole.infrastructure.dao;

import org.anole.infrastructure.model.Anole;

public interface AnoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Wed May 04 00:04:21 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Wed May 04 00:04:21 CST 2016
     */
    int insert(Anole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Wed May 04 00:04:21 CST 2016
     */
    int insertSelective(Anole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Wed May 04 00:04:21 CST 2016
     */
    Anole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Wed May 04 00:04:21 CST 2016
     */
    int updateByPrimaryKeySelective(Anole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Wed May 04 00:04:21 CST 2016
     */
    int updateByPrimaryKey(Anole record);
}