package org.tbwork.anole.common.message.s_2_c;

import lombok.Data;

import org.tbwork.anole.common.message.Message;
import org.tbwork.anole.common.message.MessageType;

@Data
public class AuthPassWithTokenMessage extends Message {

	/**
	 * Global Id of Subscriber Client.
	 */
	private int clientId; 
	
	/**
	 * Global token for certain clientId, which is 
	 * generated by the server against invalid connection.
	 */
	private int token;

	public AuthPassWithTokenMessage()
	{
		super(MessageType.S2C_AUTH_PASS);
	} 
}
