package org.anole.infrastructure;

import java.util.List;
import org.anole.infrastructure.Anole;
import org.anole.infrastructure.AnoleExample;
import org.apache.ibatis.annotations.Param;

public interface AnoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    int countByExample(AnoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    int deleteByExample(AnoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    int insert(Anole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    int insertSelective(Anole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    List<Anole> selectByExample(AnoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    Anole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    int updateByExampleSelective(@Param("record") Anole record, @Param("example") AnoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    int updateByExample(@Param("record") Anole record, @Param("example") AnoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    int updateByPrimaryKeySelective(Anole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table anole_user
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    int updateByPrimaryKey(Anole record);
}