package org.anole.infrastructure;

import java.util.Date;

public class Anole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anole_user.Id
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anole_user.Username
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anole_user.Password
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anole_user.CreateTime
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anole_user.UpdateTime
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column anole_user.Status
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    private Boolean status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anole_user.Id
     *
     * @return the value of anole_user.Id
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anole_user.Id
     *
     * @param id the value for anole_user.Id
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anole_user.Username
     *
     * @return the value of anole_user.Username
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anole_user.Username
     *
     * @param username the value for anole_user.Username
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anole_user.Password
     *
     * @return the value of anole_user.Password
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anole_user.Password
     *
     * @param password the value for anole_user.Password
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anole_user.CreateTime
     *
     * @return the value of anole_user.CreateTime
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anole_user.CreateTime
     *
     * @param createtime the value for anole_user.CreateTime
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anole_user.UpdateTime
     *
     * @return the value of anole_user.UpdateTime
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anole_user.UpdateTime
     *
     * @param updatetime the value for anole_user.UpdateTime
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column anole_user.Status
     *
     * @return the value of anole_user.Status
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    public Boolean getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column anole_user.Status
     *
     * @param status the value for anole_user.Status
     *
     * @mbggenerated Mon May 02 22:54:40 CST 2016
     */
    public void setStatus(Boolean status) {
        this.status = status;
    }
}